import 'dart:convert';
import 'package:flutter/services.dart';
import '../models/azkar_model.dart';

class AzkarService {
  static Future<List<AzkarModel>> loadAzkarList() async {
    try {
      final String jsonString = await rootBundle.loadString('assets/data/daily_azkar.json');
      final List<dynamic> data = json.decode(jsonString);
      if (data.isNotEmpty) {
        return data.map((e) => AzkarModel.fromJson(e)).toList();
      }
    } catch (_) {
      // Fallback to built-in default Azkar
    }
    return defaultAzkarList;
  }

  static List<AzkarModel> get defaultAzkarList => [
    AzkarModel(
      id: 1,
      category: 'morning',
      categoryUrdu: 'صبح کے اذکار',
      title: 'Ayat-ul-Kursi (Morning Protection)',
      titleUrdu: 'آیت الکرسی (صبح کی حفاظت)',
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      transliteration: 'Allahu la ilaha illa huwal hayyul qayyum...',
      translationUrdu: 'اللہ وہ ذات ہے جس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ رہنے والا اور سب کو سنبھالنے والا ہے...',
      translationEn: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence...',
      targetCount: 1,
      virtueUrdu: 'جو شخص صبح کے وقت پڑھے گا وہ شام تک جنات اور ہر بلا سے محفوظ رہے گا۔',
      reference: 'صحیح ابن حبان / الحاكم',
    ),
    AzkarModel(
      id: 2,
      category: 'morning',
      categoryUrdu: 'صبح کے اذکار',
      title: 'Sayyidul Istighfar (Chief of Forgiveness)',
      titleUrdu: 'سید الاستغفار',
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliteration: 'Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana \'abduka...',
      translationUrdu: 'اے اللہ! تو ہی میرا رب ہے، تیرے سوا کوئی معبود نہیں، تو نے ہی مجھے پیدا کیا اور میں تیرا بندہ ہوں...',
      translationEn: 'O Allah, You are my Lord, there is no God but You. You created me and I am Your servant...',
      targetCount: 1,
      virtueUrdu: 'جو شخص یقین کے ساتھ صبح پڑھے اور شام سے پہلے وفات پا جائے تو وہ جنتی ہے۔',
      reference: 'صحیح بخاری: 6306',
    ),
    AzkarModel(
      id: 3,
      category: 'morning',
      categoryUrdu: 'صبح کے اذکار',
      title: 'Dua for Morning Light & Guidance',
      titleUrdu: 'صبح کا شکر اور توحید',
      arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: 'Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah...',
      translationUrdu: 'ہم نے صبح کی اور اللہ کے سارے ملک نے صبح کی اور تمام تعریف اللہ ہی کے لیے ہے، اللہ کے سوا کوئی معبود نہیں...',
      translationEn: 'We have reached the morning and the whole domain belongs to Allah, praise is to Allah...',
      targetCount: 1,
      virtueUrdu: 'دن کے آغاز میں اللہ کی بادشاہی اور توحید کا اقرار۔',
      reference: 'صحیح مسلم: 2723',
    ),
    AzkarModel(
      id: 4,
      category: 'morning',
      categoryUrdu: 'صبح کے اذکار',
      title: 'Protection Against Sudden Harm',
      titleUrdu: 'ہر قسم کے نقصان سے حفاظت',
      arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      transliteration: 'Bismillahillazi la yadurru ma\'asmihi shay\'un fil ardi wa la fis sama\'i wa huwas sami\'ul \'aleem',
      translationUrdu: 'اللہ کے نام سے جس کے نام کی برکت سے زمین اور آسمان کی کوئی چیز نقصان نہیں پہنچا سکتی اور وہ خوب سننے اور جاننے والا ہے۔',
      translationEn: 'In the name of Allah, with whose name nothing in the earth or heavens can cause harm...',
      targetCount: 3,
      virtueUrdu: 'جو شخص صبح اور شام 3 مرتبہ پڑھے گا اسے کوئی ناگہانی آفت نقصان نہیں پہنچائے گی۔',
      reference: 'سنن ابی داود: 5088 / سنن ترمذی',
    ),
    AzkarModel(
      id: 5,
      category: 'morning',
      categoryUrdu: 'صبح کے اذکار',
      title: 'Raditu Billahi Rabba (Contentment with Faith)',
      titleUrdu: 'ایمان پر راضی ہونے کا اقرار',
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      transliteration: 'Radeetu billahi Rabba, wa bil Islami deena, wa bi Muhammadin sallallahu \'alayhi wa sallama Nabiyya',
      translationUrdu: 'میں اللہ کے رب ہونے، اسلام کے دین ہونے اور محمد ﷺ کے نبی ہونے پر راضی اور خوش ہوں۔',
      translationEn: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (PBUH) as my Prophet.',
      targetCount: 3,
      virtueUrdu: 'جو صبح و شام 3 بار پڑھے، اللہ پر حق ہے کہ قیامت کے دن اسے راضی کرے۔',
      reference: 'سنن ابی داود: 5072',
    ),
    AzkarModel(
      id: 6,
      category: 'evening',
      categoryUrdu: 'شام کے اذکار',
      title: 'Evening Protection Dua',
      titleUrdu: 'شام کی پناہ اور حفاظت',
      arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: 'Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah...',
      translationUrdu: 'ہم نے شام کی اور اللہ کے سارے ملک نے شام کی اور تمام تعریف اللہ کے لیے ہے...',
      translationEn: 'We have reached the evening and the whole domain belongs to Allah...',
      targetCount: 1,
      virtueUrdu: 'رات کے شر اور ہر مصیبت سے پناہ۔',
      reference: 'صحیح مسلم: 2723',
    ),
    AzkarModel(
      id: 7,
      category: 'evening',
      categoryUrdu: 'شام کے اذکار',
      title: 'Seeking Refuge from Harm of Creations',
      titleUrdu: 'زہریلے جانوروں اور شر سے حفاظت',
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      transliteration: 'A\'oodhu bi kalimatillahi-t-tammati min sharri ma khalaq',
      translationUrdu: 'میں اللہ کے تمام کامل کلمات کی پناہ مانگتا ہوں اس کی تمام مخلوقات کے شر سے۔',
      translationEn: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      targetCount: 3,
      virtueUrdu: 'جو شام کو 3 بار پڑھے گا اسے اس رات بچھو یا کوئی زہریلا جانور نقصان نہیں پہنچائے گا۔',
      reference: 'صحیح مسلم: 2709',
    ),
    AzkarModel(
      id: 8,
      category: 'evening',
      categoryUrdu: 'شام کے اذکار',
      title: 'Last 2 Verses of Surah Al-Baqarah',
      titleUrdu: 'آمن الرسول (سورۃ البقرہ کی آخری آیات)',
      arabic: 'آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ',
      transliteration: 'Amanar-rasoolu bima unzila ilayhi mir-rabbihi wal mu\'minoon...',
      translationUrdu: 'رسول نے اس پر ایمان لایا جو اس کے رب کی طرف سے نازل کیا گیا اور مومنوں نے بھی...',
      translationEn: 'The Messenger has believed in what was revealed to him from his Lord, and [so have] the believers...',
      targetCount: 1,
      virtueUrdu: 'جو رات کو یہ دو آیات پڑھے گا وہ اس کے لیے (ہر آفت و بلا سے) کافی ہو جائیں گی۔',
      reference: 'صحیح بخاری: 5009',
    ),
    AzkarModel(
      id: 9,
      category: 'after_prayer',
      categoryUrdu: 'نماز کے بعد کے اذکار',
      title: 'Istighfar & As-Salam After Prayer',
      titleUrdu: 'استغفار اور سلامتی کی دعا',
      arabic: 'أَسْتَغْفِرُ اللَّهَ (٣ مرات)\nاللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
      transliteration: 'Astaghfirullah (3 times)\nAllahumma antas-Salamu wa minkas-Salam, tabarakta ya dhal Jalali wal-Ikram',
      translationUrdu: 'میں اللہ سے بخشش مانگتا ہوں (3 بار)\nاے اللہ! تو سلامتی والا ہے اور تجھی سے سلامتی ہے، تو برکت والا ہے اے عظمت اور بزرگی والے۔',
      translationEn: 'I ask Allah for forgiveness (3x). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of Majesty and Honor.',
      targetCount: 1,
      virtueUrdu: 'نبی کریم ﷺ ہر فرض نماز کے سلام پھیرنے کے بعد یہ پڑھتے تھے۔',
      reference: 'صحیح مسلم: 591',
    ),
    AzkarModel(
      id: 10,
      category: 'after_prayer',
      categoryUrdu: 'نماز کے بعد کے اذکار',
      title: 'Tasbih Fatimi (Post Prayer)',
      titleUrdu: 'تسبیح فاطمی (سبحان اللہ، الحمد للہ، اللہ اکبر)',
      arabic: 'سُبْحَانَ اللَّهِ (٣٣ بار)\nالْحَمْدُ لِلَّهِ (٣٣ بار)\nاللَّهُ أَكْبَرُ (٣٣ بار)\nلَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ (١ بار)',
      transliteration: 'SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (33x), La ilaha illallahu wahdahu la shareeka lah...',
      translationUrdu: 'اللہ پاک ہے (33 مرتبہ)، تمام تعریفیں اللہ کے لیے ہیں (33 مرتبہ)، اللہ سب سے بڑا ہے (33 مرتبہ)، اور آخر میں کلمہ توحید (1 مرتبہ)',
      translationEn: 'Glory be to Allah (33x), Praise be to Allah (33x), Allah is the Greatest (33x), followed by Kalima Tauheed once.',
      targetCount: 100,
      virtueUrdu: 'جو ہر نماز کے بعد یہ پڑھے اس کے گناہ معاف کر دیے جاتے ہیں چاہے سمندر کی جھاگ کے برابر ہوں۔',
      reference: 'صحیح مسلم: 597',
    ),
    AzkarModel(
      id: 11,
      category: 'sleep',
      categoryUrdu: 'سوتے وقت کے اذکار',
      title: 'Dua Before Sleeping',
      titleUrdu: 'سوتے وقت کی مسنون دعا',
      arabic: 'اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا',
      transliteration: 'Allahumma bismika amootu wa ahya',
      translationUrdu: 'اے اللہ! میں تیرے نام کے ساتھ ہی مرتا (سوتا) ہوں اور جیتا (جاگتا) ہوں۔',
      translationEn: 'O Allah, with Your name I die and I live.',
      targetCount: 1,
      virtueUrdu: 'نیند میں اللہ کی پناہ اور حفاظت حاصل کرنے کی سنت دعا۔',
      reference: 'صحیح بخاری: 6312',
    ),
    AzkarModel(
      id: 12,
      category: 'protection',
      categoryUrdu: 'حفاظت اور شفا',
      title: 'Ayat-e-Kareema (Relief from Distress)',
      titleUrdu: 'آیت کریمہ (حضرت یونس علیہ السلام کی دعا)',
      arabic: 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
      transliteration: 'La ilaha illa anta subhanaka inni kuntu minaz-zalimeen',
      translationUrdu: 'تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ہی قصورواروں میں سے ہوں۔',
      translationEn: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
      targetCount: 33,
      virtueUrdu: 'جو مسلمان کسی مصیبت یا مشکل میں یہ دعا کرے گا، اللہ اس کی دعا ضرور قبول فرمائے گا۔',
      reference: 'جامع ترمذی: 3505',
    ),
  ];
}
